### ISSUE TITLE
We're not defining any spacing rules

### ISSUE THREAD

**Issue by jonlay** [wearehanno/pillars#4]
I think we need to get this done, and make it really prominent, because it's frequently controversial.

Do we use spaces, or tabs for indentation. Both in Sass, and also JS and HTML? And how many of each do we use.

@marcelkalveram may want to chime in here, particularly as there will be overlap with any JS, PHP, and Rails code that we write.

**Comment by marcelkalveram** [comment]
I usually use tabs, but from a formatting standpoint, their seems to be a tendency to use spacing instead. That's no problem for me because I can easily tell Sublime to create two or four spaces when I hit tab.

IMO we should go for 2 spaces in whatever kind of markup/programming language we're working on, to have consistency across all docs.

**Comment by jonlay** [comment]
That works for me. I’ll leave you guys to implement that.

It’d also be a nice idea, for less experienced developers, to create a “Hanno sublime config” and keep this in Pillars too? That could give us consistency across team coding environments, even if it just has a few settings we need to copy into our configs.

**Comment by sergeitatarinov** [comment]
I defined it in the General Formatting rules here https://github.com/wearehanno/pillars/tree/master/style as I'd thought it applies to every language etc. Thoughts?

**Comment by jonlay** [comment]
Ahh, i must have missed that. I find "style" to be a bit misleading if we're talking about standards to be applied to all languages (including JS, PHP etc). I suppose you guys will need to tweak the organisation a little bit, so that the directories and organisation are a bit more logical?

**Comment by sergeitatarinov** [comment]
Can we simply change the 'style' to something else, for instance 'global' or 'standards'?

**Comment by jonlay** [comment]
Sure--whatever works. Just needs to be changed from the current version.

Style was originally supposed to mean styling guidelines. So if it's not being used for that, you might even want to question whether a 'container' directory is needed. Could just keep the `/css` and `/html` documentaries and remote the container.
