### ISSUE TITLE
No example templates

### ISSUE THREAD

**Issue by jonlay** [wearehanno/pillars#5]
@sergeitatarinov One big thing for me: I'd really like to re-introduce the "perfect example templates".

So that you'd have a perfectly organised Sass file inside the repo, which demonstrates a bunch of things, and which people can download and use for reference. Would it be possible for you to create a Sass one and drop it in?

**Comment by marcelkalveram** [comment]
That would be pretty cool indeed. I'd be eager to pair on this on Monday.

**Comment by sergeitatarinov** [comment]
I've put together an example stylesheet (https://github.com/wearehanno/pillars/blob/master/sass/example.scss) have a quick look if you have time?

@marcelkalveram @jonlay I've got a few improvements in mind already, let's come back to it later this week once I've gathered my thoughts. There's plenty to discuss but I'm super busy today.

I think this is shippable now.

**Comment by jonlay** [comment]
Looks good!
