### ISSUE TITLE
Styling all footers, in example.scss

### ISSUE THREAD

**Issue by jonlay** [wearehanno/pillars#7]
Hey, spotted this in example.scss:

https://github.com/wearehanno/pillars/blob/master/sass/example.scss#L199

    footer {
        margin-top: ($vertical-spacing / 2);

        @media #{$medium-up} {
            margin-top: $vertical-spacing;
        }
    }

Is it not quite a bad idea to be styling every single `footer` element in the entire app/site, with these margin tops, etc?

Footer is something which might be used all over the place, inside multiple sections. This seems like it might be a bad example to use in the "perfect" example stylesheet? :wink:

**Comment by sergeitatarinov** [comment]
@jonlay Cheers. Fixed it. Still getting the hang of the new rules myself. My tattoo should be altered to say 'Never Nesting' ;)
