### ISSUE TITLE
Requires an example.html file

### ISSUE THREAD

**Issue by jonlay** [wearehanno/pillars#9]
As with `example.scss`, we need this one to provide more concrete sample Javascript for users to learn from :smile:

This one should also match up a little with the stuff we have in `example.scss`, so where possible, the two can be viewed as compatible. Although obviously all the styles for an `example.html` won't be inside the scss file.

Maybe the `example.html ` could be a full regular HTML page, marked up 'perfectly'?

**Comment by sergeitatarinov** [comment]
Added it here: https://github.com/wearehanno/pillars/blob/master/html/example.html

**Comment by jonlay** [comment]
Cheers!
